
name: GITHUB ACTION TEST

on:
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: alpine:3.9
    env: 
      DOCKER_DRIVER: overlay
      SSH_GITLAB_KEY: $SSH_PRIVATE_KEY
      IMAGE_NAME: $CI_PRIVATE_REGISTRY/platform/$CI_PROJECT_NAME
      IMAGE_TAG: $CI_COMMIT_SHORT_SHA
      npm_config_cache: "$CI_PROJECT_DIR/.npm"
      CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
      CHART_NAME: www
      CHART_REPO: https://$CI_PRIVATE_REGISTRY/chartrepo/platform
      GIT_STRATEGY: fetch
      GIT_DEPTH: 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
